name = "bun-hono-cloudflare"
compatibility_date = "2023-12-01"

[vars]
MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "bun-hono-cloudflare-d1"
database_id = "a79e06af-21b5-438f-8fd5-a1cf5cd71eb4"
